/**
 * @private 
 * @type {Object}
 * @properties={typeid:35,uuid:"A2D0E9D1-476A-4F7A-81C9-CC02AEC98D6C",variableType:-4}
 */
var state

/**
 * @properties={typeid:24,uuid:"BAC0C153-4B5E-43AA-BC17-AA0456795221"}
 */
function toObjectPresentation() {
	return {
		svySpecial: true,
		type: '',
		
	}
}

//Chart Methods
/**
 * @param {Array<Array<String>>|Array<Array<String, Number>>|Array<Array<String, Number>>|Array<Array<Number, Number>>|Array<Array<Number, Number, Number>>|Array<Array<Number, Number, Number, Number>>} data See https://developers.google.com/chart/interactive/docs/gallery/geochart#Data_Format
 * @param {Object} options
 * @param options.backgroundColor {String|Object} default='white'  The background color for the main area of the chart. Can be either a simple HTML color string, for example: 'red' or '#00cc00', or an object with the following properties.                                                                                                                                                                                                                                                                                                                                
 * @param options.backgroundColor.fill {String} default='white' The chart fill color, as an HTML color string.                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 * @param options.backgroundColor.stroke {String} default='#666' The color of the chart border, as an HTML color string.                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 * @param options.backgroundColor.strokeWidth {Number}	default=0 The border width, in pixels.                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 * @param options.colorAxis {Object} default=null An object that specifies a mapping between color column values and colors or a gradient scale. To specify properties of this object, you can use object literal notation, as shown here: {minValue: 0, colors: ['#FF0000', '#00FF00']}                                                                                                                                                                                                                                                                     
 * @param options.colorAxis.minValue {Number} default=Minimum value of color column in chart data. If present, specifies a minimum value for chart color data. Color data values of this value and lower will be rendered as the first color in the colorAxis.colors range.                                                                                                                                                                                                                                                                                                                                   
 * @param options.colorAxis.maxValue {Number} default=Maximum value of color column in chart data. If present, specifies a maximum value for chart color data. Color data values of this value and higher will be rendered as the last color in the colorAxis.colors range.                                                                                                                                                                                                                                                                                                                                   
 * @param options.colorAxis.values {Array<Number>} default=null, if present, controls how values are associated with colors. Each value is associated with the corresponding color in the colorAxis.colors array. These values apply to the chart color data. Coloring is done according to a gradient of the values specified here. Not specifying a value for this option is equivalent to specifying [minValue, maxValue].                                                                                                                                               
 * @param options.colorAxis.colors {Array<Strin(g>} default=null Colors to assign to values in the visualization. An array of strings, where each element is an HTML color string, for example: colorAxis: {colors:['red','#004411']}. You must have at least two values; the gradient will include all your values, plus calculated intermediary values, with the first color as the smallest value, and the last color as the highest.                                                                                                                                    
 * @param options.datalessRegionColor {String}	default='F5F5F5' Colors to assign to regions with no associated data.                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 * @param options.displayMode {String}	default='auto' Which type of map this is. The DataTable format must match the value specified. The following values are supported: 'auto' - Choose based on the format of the DataTable. 'regions' - This is a region map 'markers' - This is a marker map.                                                                                                                                                                                                                                                               
 * @param options.enableRegionInteractivity {Boolean} default=true If true, enable region interactivity, including focus and tool-tip elaboration on mouse hover, and region selection and firing of regionClick and select events on mouse click. The default is true in region mode, and false in marker mode.                                                                                                                                                                                                                                                              
 * @param options.height {Number}	default='auto' Height of the visualization, in pixels. The default height is 347 pixels, unless the width option is specified and keepAspectRatio is set to true - in which case the height is calculated accordingly.                                                                                                                                                                                                                                                                                                    
 * @param options.keepAspectRatio {Boolean} default=true If true, the map will be drawn at the largest size that can fit inside the chart area at its natural aspect ratio. If only one of the width and height options is specified, the other one will be calculated according to the aspect ratio. If false, the map will be stretched to the exact size of the chart as specified by the width and height options.                                                                                                                                              
 * @param options.legend {Object|String} default=null An object with members to configure various aspects of the legend, or 'none', if no legend should appear. To specify properties of this object, you can use object literal notation, as shown here: {textStyle: {color: 'blue', fontSize: 16}}                                                                                                                                                                                                                                                             
 * @param options.legend.numberFormat {String}	default='auto' A format string for numeric labels. This is a subset of the ICU pattern set. For instance, {numberFormat:'.##'} will display values "10.66", "10.6", and "10.0" for values 10.666, 10.6, and 10.                                                                                                                                                                                                                                                                                                           
 * @param options.legend.textStyle {Object} default={color: 'black', fontName: <global-font-name>, fontSize: <global-font-size>}	An object that specifies the legend text style. The object has this format: {color: <string>, fontName: <string>, fontSize: <number>} The color can be any HTML color string, for example: 'red' or '#00cc00'. Also see fontName and fontSize.                                                                                                                                                                                                                                                             
 * @param options.region {String} default='world' The area to display on the map. (Surrounding areas will be displayed as well.) Can be one of the following: 'world' - A map of the entire world. A continent or a sub-continent, specified by its 3-digit code, e.g., '011' for Western Africa. A country, specified by its ISO 3166-1 alpha-2 code, e.g., 'AU' for Australia. A state in the United States, specified by its ISO 3166-2:US code, e.g., 'US-AL' for Alabama. Note that the resolution option must be set to either 'provinces' or 'metros'.
 * @param options.magnifyingGlass {Object}	default={enable: true, zoomFactor: 5.0} An object with members to configure various aspects of the magnifying glass. To specify properties of this object, you can use object literal notation, as shown here: {enable: true, zoomFactor: 7.5}                                                                                                                                                                                                                                                                                                     
 * @param options.magnifyingGlass.enable {Boolean}	default=true If true, when the user lingers over a cluttered marker, a magnifiying glass will be opened. Note: this feature is not supported in browsers that do not support SVG, i.e. Internet Explorer version 8 or earlier.                                                                                                                                                                                                                                                                                          
 * @param options.magnifyingGlass.zoomFactor {Number} default=5.0 The zoom factor of the magnifying glass. Can be any number greater than 0.                                                                                                                                                                                                                                                                                                                                                                                                                                 
 * @param options.markerOpacity {Number} default=1.0 The opacity of the markers, where 0.0 is fully transparent and 1.0 is fully opaque.                                                                                                                                                                                                                                                                                                                                                                                                                        
 * @param options.resolution {String} default='countries' The resolution of the map borders. Choose one of the following values: 'countries' - Supported for all regions, except for US state regions. 'provinces' - Supported only for country regions and US state regions. Not supported for all countries; please test a country to see whether this option is supported. 'metros' - Supported for the US country region and US state regions only.                                                                                                              
 * @param options.sizeAxis {Object}  default=null An object with members to configure how values are associated with bubble size. To specify properties of this object, you can use object literal notation, as shown here: {minValue: 0, maxSize: 20}                                                                                                                                                                                                                                                                                                       
 * @param options.sizeAxis.maxSize {Number} default=12 Maximum radius of the largest possible bubble, in pixels.                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 * @param options.sizeAxis.maxValue {Number} default=Maximum value of size column in chart data. The size value (as appears in the chart data) to be mapped to sizeAxis.maxSize. Larger values will be cropped to this value.                                                                                                                                                                                                                                                                                                                                                                               
 * @param options.sizeAxis.minSize {Number} default=3, Mininum radius of the smallest possible bubble, in pixels.                                                                                                                                                                                                                                                                                                                                                                                                                                                 
 * @param options.sizeAxis.minValue {Number} default=Minimum value of size column in chart data. The size value (as appears in the chart data) to be mapped to sizeAxis.minSize. Smaller values will be cropped to this value.                                                                                                                                                                                                                                                                                                                                                                              
 * @param options.tooltip {Object}	default=null An object with members to configure various tooltip elements. To specify properties of this object, you can use object literal notation, as shown here: {textStyle: {color: '#FF0000'}, showColorCode: true}                                                                                                                                                                                                                                                                                               
 * @param options.tooltip.textStyle {Object} default={color: 'black', fontName: <global-font-name>, fontSize: <global-font-size>}	An object that specifies the tooltip text style. The object has this format: {color: <string>, fontName: <string>, fontSize: <number>} The color can be any HTML color string, for example: 'red' or '#00cc00'.                                                                                                                                                                                                                                                                                            
 * @param options.width {Number} default='auto' Width of the visualization, in pixels. The default width is 556 pixels, unless the height option is specified and keepAspectRatio is set to true - in which case the width is calculated accordingly.                                                                                                                                                                                                                                                                                                      
 *
 * @properties={typeid:24,uuid:"5819BC4D-08C4-4FED-84B5-4058C6F5E3B5"}
 */
function draw(data, options) {
	state.options = options
	state.data = data
}

/**
 * @properties={typeid:24,uuid:"03F5694D-0D49-485B-8F33-205363E5829D"}
 */
function getSelection(){}

/**
 * @properties={typeid:24,uuid:"3B7C92E2-D266-49E0-8E5C-B3B8117026C7"}
 */
function setSelection(){}

/**
 * @properties={typeid:24,uuid:"325A64FB-2B0E-4A0E-9284-A784462E2AC9"}
 */
function clearChart(){}

/**
 * @properties={typeid:24,uuid:"4A1B9A30-6DC6-46FE-A88A-91A2AD7421A9"}
 */
function addEventListener() {
	
}
  

/**
 * @properties={typeid:24,uuid:"90758771-6C8A-424E-A775-A4CDF4538791"}
 */
function getBrowserId() {
	return 'geochart'
}
